from typing import Protocol


class QueryBackend(Protocol):
    """Abstract interface for database backends. Add a new backend by implementing all methods."""

    def explain(self, query: str) -> dict: ...
    def explain_analyze(self, query: str, timeout_s: int | None = None) -> dict: ...
    def validate_syntax(self, query: str) -> tuple[bool, str]: ...
    def extract_references(self, query: str) -> set[str]: ...
    def sample_hash(self, query: str, timeout_s: int | None = None, uri: str | None = None) -> tuple[str | None, str | None]: ...
    def get_total_cost(self, explain_result: dict) -> float | None: ...
    def extract_table_estimates(self, explain_result: dict) -> dict[str, int]: ...
    def syntax_hint(self) -> str: ...
    def hardware_hints(self) -> dict: ...
    def sqlglot_dialect(self) -> str: ...
    def get_partial_index_predicates(self, table_name: str) -> dict[str, str]: ...
    def parse_query(self, query: str) -> dict | None: ...
    def decorrelate(self, components: dict) -> str | None: ...  # seeded deterministic decorrelation (arch A)
    def consolidate(self, components: dict) -> str | None: ...  # seeded deterministic consolidation (arch A)
    def bucket_agg_expr(self, agg_node, pred_node) -> str: ...  # dialect hook: PG FILTER vs MySQL CASE WHEN
    # DETECTOR-ONLY decomposed dispatcher — the architect node calls ONLY this and reads back provenance;
    # it never names a transform. Iterates the backend's transform registry (closed set of deterministic
    # detectors): structural recognize -> shared builder. NO LLM in production. Returns
    # (sql|None, provenance{transform, trigger, suggestions}); (None, ...) -> production leaves unchanged.
    def optimize_decomposed(self, raw_sql: str, components: dict) -> tuple[str | None, dict]: ...
    def build_optimization_prompt(
        self,
        components: dict,
        explain: dict,
        hw_hints: dict,
        schema_context: dict | None = None,
        errors: list[str] | None = None,
        retry_hint: str | None = None,
        table_estimates: dict | None = None,
    ) -> str: ...
    def build_fallback_prompt(self, raw_query: str, explain: dict, errors: list[str], hw_hints: dict, retry_hint: str | None, prior_attempts: list[str] | None = None) -> str: ...
    # Corrector (WRITE-axis repair) — engine-specific prompt + failure taxonomy. The corrector NODE
    # and the routing are paradigm-agnostic orchestration; these supply the SQL/NoSQL-specialist knowledge.
    # corrector_should_fire is the AGNOSTIC gate the routing calls — "is this a mechanical failure on an
    # attempt worth the (budgeted) corrector?" — keeping the engine's failure/targeting taxonomy off the graph.
    def corrector_should_fire(self, errors: list[str], raw_sql: str, optimized_sql: str) -> bool: ...
    def is_mechanical_failure(self, errors: list[str]) -> bool: ...
    def sanitize_corrector_errors(self, errors: list[str]) -> list[str]: ...
    def build_corrector_prompt(self, original: str, broken: str, errors: list[str], history: str = "") -> str: ...
    # PROVE the corrector only repaired (did not change the optimization strategy). Agnostic node calls
    # it; the engine-specific structural check lives on the backend. False ⇒ the node discards the repair.
    def corrector_preserved_strategy(self, original: str, broken: str, repaired: str) -> bool: ...
    def extract_query(self, text: str) -> str: ...
    def check_structural_integrity(self, raw_query: str, optimized_query: str) -> list[str]: ...
    def causal_regression_hint(self, optimized_query: str) -> str | None: ...
    # Reflection hint for the REASONING model (architect) when an APPLIED technique is only half-done
    # (e.g. correlated subquery still present after decorrelation). Engine-specific; the corrector must
    # NOT receive it — completing the technique is optimization, which must come from the reasoning model.
    def incomplete_technique_hint(self, raw_query: str, optimized_query: str) -> str | None: ...
    def extract_schema(self) -> tuple[list[dict], list[dict]]: ...
    def ping_latency(self) -> float: ...
    def db_version(self) -> str: ...
    def run_analyze(self, tables: list[str]) -> None: ...
    def generate_index_ddl(self, spec: dict) -> str | None: ...
    def schema_fingerprint(self) -> str | None: ...
    def is_timeout_error(self, error_message: str) -> bool: ...
    def simulate_index(self, spec: dict, query: str, workload: list[dict] | None = None) -> dict: ...
    def existing_index_covering(self, table: str, columns: list[str], index_type: str) -> str | None: ...
    def build_index_advisor_prompt(self, query: str, explain: dict, schema_context: dict, query_tables: set[str], suggestions: list[str] | None = None, workload_digest: str | None = None) -> str: ...
